/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-09-27 18:11:55 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/skills_api -t resources -t competency_group_competencies -t resource_competencies -t assessments -t team_memberships -t skill_categories -t position_requirements -t competencies -t skills -t competency_groups -t project_teams -t skill_categorizations -t competency_requirements -t positions -t missions -t projects -s public
 *
 */


export namespace resourcesFields {
  export type id = number;
  export type first_name = string;
  export type last_name = string;
  export type employee_number = string;
  export type email = string | null;

}

export interface resources {
  id: resourcesFields.id;
  first_name: resourcesFields.first_name;
  last_name: resourcesFields.last_name;
  employee_number: resourcesFields.employee_number;
  email: resourcesFields.email;

}

export namespace competency_group_competenciesFields {
  export type competency_id = number;
  export type competency_group_id = number;

}

export interface competency_group_competencies {
  competency_id: competency_group_competenciesFields.competency_id;
  competency_group_id: competency_group_competenciesFields.competency_group_id;

}

export namespace resource_competenciesFields {
  export type resource_id = number | null;
  export type competency_id = number | null;
  export type assessed_on = Date;
  export type validation_date = Date | null;
  export type validator_id = number | null;
  export type is_validated = boolean;
  export type is_pending_validation = boolean;

}

export interface resource_competencies {
  resource_id: resource_competenciesFields.resource_id;
  competency_id: resource_competenciesFields.competency_id;
  assessed_on: resource_competenciesFields.assessed_on;
  validation_date: resource_competenciesFields.validation_date;
  validator_id: resource_competenciesFields.validator_id;
  is_validated: resource_competenciesFields.is_validated;
  is_pending_validation: resource_competenciesFields.is_pending_validation;

}

export namespace assessmentsFields {
  export type id = number;
  export type resource_id = number;
  export type competency_requirement_id = number;
  export type due_date = Date | null;
  export type created_at = Date;
  export type updated_at = Date;
  export type submitted_at = Date;
  export type validated_at = Date;
  export type is_open = boolean;
  export type is_filled = boolean;
  export type is_submitted = boolean;
  export type is_validated = boolean;

}

export interface assessments {
  id: assessmentsFields.id;
  resource_id: assessmentsFields.resource_id;
  competency_requirement_id: assessmentsFields.competency_requirement_id;
  due_date: assessmentsFields.due_date;
  created_at: assessmentsFields.created_at;
  updated_at: assessmentsFields.updated_at;
  submitted_at: assessmentsFields.submitted_at;
  validated_at: assessmentsFields.validated_at;
  is_open: assessmentsFields.is_open;
  is_filled: assessmentsFields.is_filled;
  is_submitted: assessmentsFields.is_submitted;
  is_validated: assessmentsFields.is_validated;

}

export namespace team_membershipsFields {
  export type team_id = number;
  export type resource_id = number;

}

export interface team_memberships {
  team_id: team_membershipsFields.team_id;
  resource_id: team_membershipsFields.resource_id;

}

export namespace skill_categoriesFields {
  export type id = number;
  export type name = string;
  export type display_name = string;
  export type created_at = Date;
  export type updated_at = Date;

}

export interface skill_categories {
  id: skill_categoriesFields.id;
  name: skill_categoriesFields.name;
  display_name: skill_categoriesFields.display_name;
  created_at: skill_categoriesFields.created_at;
  updated_at: skill_categoriesFields.updated_at;

}

export namespace position_requirementsFields {
  export type position_id = number | null;
  export type competency_id = number | null;

}

export interface position_requirements {
  position_id: position_requirementsFields.position_id;
  competency_id: position_requirementsFields.competency_id;

}

export namespace competenciesFields {
  export type id = number;
  export type skill_id = number | null;
  export type level = number | null;

}

export interface competencies {
  id: competenciesFields.id;
  skill_id: competenciesFields.skill_id;
  level: competenciesFields.level;

}

export namespace skillsFields {
  export type id = number;
  export type name = string;
  export type display_name = string;
  export type created_at = Date;
  export type updated_at = Date;

}

export interface skills {
  id: skillsFields.id;
  name: skillsFields.name;
  display_name: skillsFields.display_name;
  created_at: skillsFields.created_at;
  updated_at: skillsFields.updated_at;
}

export namespace competency_groupsFields {
  export type id = number;
  export type position_id = number;
  export type name = string;

}

export interface competency_groups {
  id: competency_groupsFields.id;
  position_id: competency_groupsFields.position_id;
  name: competency_groupsFields.name;

}

export namespace project_teamsFields {
  export type id = number;
  export type project_id = number;
  export type name = string;

}

export interface project_teams {
  id: project_teamsFields.id;
  project_id: project_teamsFields.project_id;
  name: project_teamsFields.name;

}

export namespace skill_categorizationsFields {
  export type skill_id = number;
  export type category_id = number;

}

export interface skill_categorizations {
  skill_id: skill_categorizationsFields.skill_id;
  category_id: skill_categorizationsFields.category_id;

}

export namespace competency_requirementsFields {
  export type id = number;
  export type position_id = number | null;
  export type competency_id = number | null;
  export type description = string | null;
  export type created_at = Date;
  export type updated_at = Date;

}

export interface competency_requirements {
  id: competency_requirementsFields.id;
  position_id: competency_requirementsFields.position_id;
  competency_id: competency_requirementsFields.competency_id;
  description: competency_requirementsFields.description;
  created_at: competency_requirementsFields.created_at;
  updated_at: competency_requirementsFields.updated_at;

}

export namespace positionsFields {
  export type id = number;
  export type project_id = number;
  export type name = string | null;
  export type display_name = string | null;
  export type description = string | null;

}

export interface positions {
  id: positionsFields.id;
  project_id: positionsFields.project_id;
  name: positionsFields.name;
  display_name: positionsFields.display_name;
  description: positionsFields.description;

}

export namespace missionsFields {
  export type id = number;
  export type resource_id = number | null;
  export type project_id = number | null;
  export type position_id = number | null;
  export type start_date = Date;
  export type end_date = Date;
  export type is_active = boolean;

}

export interface missions {
  id: missionsFields.id;
  resource_id: missionsFields.resource_id;
  project_id: missionsFields.project_id;
  position_id: missionsFields.position_id;
  start_date: missionsFields.start_date;
  end_date: missionsFields.end_date;
  is_active: missionsFields.is_active;

}

export namespace projectsFields {
  export type id = number;
  export type name = string;
  export type project_otp_code = string | null;
  export type start_date = Date | null;
  export type end_date = Date | null;

}

export interface projects {
  id: projectsFields.id;
  name: projectsFields.name;
  project_otp_code: projectsFields.project_otp_code;
  start_date: projectsFields.start_date;
  end_date: projectsFields.end_date;

}
